language: bash

services:
- docker

sudo: required

env:
- ACTION=check  TARGET=x86_64
- ACTION=build  TARGET=x86_64

before_install:
- env
- docker images
- docker info
- docker version
- df -h

script:
- if [ "$ACTION" = "check" ]; then cd ${TRAVIS_BUILD_DIR}/Linux && make           travis_check; fi
- if [ "$ACTION" = "build" ]; then cd ${TRAVIS_BUILD_DIR}/Linux && make           travis_build; fi
- ls -laR
